# Generated by Django 6.0.5 on 2026-05-26 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='time_taken',
            field=models.FloatField(default=0),
        ),
    ]
